# Generated by Django 5.0.3 on 2024-04-22 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_ID', models.IntegerField(max_length=3)),
                ('Teacher_Name', models.CharField(max_length=50)),
                ('Teacher_Department', models.TextField(choices=[('MBA', 'MBA'), ('B.TECH', 'B.TECH'), ('B.SC', 'B.SC'), ('BCA', 'BCA')])),
                ('Teacher_Degree', models.TextField(choices=[('MBA', 'MBA'), ('B.TECH', 'B.TECH'), ('B.SC', 'B.SC'), ('BCA', 'BCA')])),
            ],
        ),
    ]
